[workspace]

members = [
  "abstio",
  "abstutil",
  "collisions",
  "convert_osm",
  "fifteen_min",
  "game",
  "geom",
  "headless",
  "importer",
  "kml",
  "map_editor",
  "map_gui",
  "map_model",
  "osm_viewer",
  "parking_mapper",
  "popdat",
  "santa",
  "sim",
  "sumo",
  "tests",
  "traffic_seitan",
  "traffic_signal_data",
  "updater",
  "widgetry",
  "widgetry_demo",
]

# See https://doc.rust-lang.org/cargo/reference/profiles.html#overrides. This
# compiles all external dependencies as release mode, yielding great runtime
# speed, but only paying the cost of slow compilation once (since we don't
# update dependencies often).
[profile.dev.package."*"]
opt-level = 3

[patch.crates-io]
# Use upstream after https://github.com/flatgeobuf/flatgeobuf/pull/107 is merged and there's a new version
flatgeobuf = { git = "https://github.com/pka/flatgeobuf", branch = "geozero-0.7" }

# update to geo-types 0.7 - upstream: https://github.com/21re/rust-geo-booleanop/pull/27
geo-booleanop = { git = "https://github.com/michaelkirk/rust-geo-booleanop", branch = "mkirk/geo-types-0.7" }

# update to geo-types 0.7 - upstream: https://github.com/georust/geozero/pull/5
geozero = { git = "https://github.com/georust/geozero" }

# update to geo-types 0.7 - upstream: https://github.com/mthh/contour-rs/pull/2
contour = { git = "https://github.com/michaelkirk/contour-rs", branch = "mkirk/geojson-0.22" }

# update to geo-types 0.7 not released yet
gdal = { git = "https://github.com/georust/gdal" }
